let property_types = [
  { id: "1", type: "Apartamento", icono: "🏢" },
  { id: "2", type: "Casa", icono: "🏠" },
  { id: "3", type: "Villa", icono: "🏰" },
  { id: "4", type: "Casa adosada", icono: "🏘️" },
  { id: "5", type: "Loft", icono: "🏭" },
  { id: "6", type: "Habitación privada", icono: "🛌" },
  { id: "7", type: "Habitación compartida", icono: "🛌" },
  { id: "8", type: "Cabaña", icono: "🏡" },
  { id: "9", type: "Castillo", icono: "🏰" },
  { id: "10", type: "Barco", icono: "🛳️" },
  { id: "11", type: "Iglú", icono: "🏠" },
  { id: "12", type: "Caravana", icono: "🚐" },
  { id: "13", type: "Casa de huéspedes", icono: "🏠" },
  { id: "14", type: "Bungalow", icono: "🏡" },
  { id: "15", type: "Ático", icono: "🏢" },
  { id: "16", type: "Chalé", icono: "🏠" },
  { id: "17", type: "Rancho", icono: "🏡" },
  { id: "18", type: "Departamento", icono: "🏢" },
  { id: "19", type: "Suite de hotel", icono: "🏨" },
  { id: "20", type: "Casa cueva", icono: "🏠" },
  { id: "21", type: "Granja", icono: "🏡" },
  { id: "22", type: "Lodge", icono: "🏨" },
  { id: "23", type: "Molino", icono: "🏭" },
  { id: "24", type: "Chalet alpino", icono: "🏔️" },
  { id: "25", type: "Casa de campo", icono: "🏡" },
  { id: "26", type: "Torre", icono: "🗼" },
  { id: "27", type: "Casa de vacaciones", icono: "🏡" },
  { id: "28", type: "Casa de playa", icono: "🏖️" },
  { id: "29", type: "Casa flotante", icono: "🚣" },
  { id: "30", type: "Departamento en complejo residencial", icono: "🏢" },
  { id: "31", type: "Apartotel", icono: "🏢" },
];

module.exports = { property_types };
